[2025-06-29T09:54:34.100+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-29T09:54:34.119+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-29T09:54:27.074958+00:00 [queued]>
[2025-06-29T09:54:34.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-29T09:54:27.074958+00:00 [queued]>
[2025-06-29T09:54:34.124+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-29T09:54:34.131+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-06-29 09:54:27.074958+00:00
[2025-06-29T09:54:34.146+0000] {standard_task_runner.py:63} INFO - Started process 59 to run task
[2025-06-29T09:54:34.152+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2025-06-29T09:54:27.074958+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpzflhmli2']
[2025-06-29T09:54:34.161+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask s3_upload
[2025-06-29T09:54:34.202+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-29T09:54:27.074958+00:00 [running]> on host b1203407efc8
[2025-06-29T09:54:34.250+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naspuka' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-06-29T09:54:27.074958+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-29T09:54:27.074958+00:00'
[2025-06-29T09:54:34.251+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-29T09:54:34.261+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-29T09:54:34.262+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 6, in upload_s3_pipeline
    file_path = ti.xcom.pull(task_ids='reddit_extraction', keys='return_value')
AttributeError: 'TaskInstance' object has no attribute 'xcom'
[2025-06-29T09:54:34.269+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=manual__2025-06-29T09:54:27.074958+00:00, execution_date=20250629T095427, start_date=20250629T095434, end_date=20250629T095434
[2025-06-29T09:54:34.274+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task s3_upload ('TaskInstance' object has no attribute 'xcom'; 59)
[2025-06-29T09:54:34.295+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-29T09:54:34.314+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-29T09:54:34.315+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
