[2025-06-29T01:07:03.436+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-29T01:07:03.469+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2025-06-28T00:00:00+00:00 [queued]>
[2025-06-29T01:07:03.474+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2025-06-28T00:00:00+00:00 [queued]>
[2025-06-29T01:07:03.474+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-29T01:07:03.483+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-06-28 00:00:00+00:00
[2025-06-29T01:07:03.494+0000] {standard_task_runner.py:63} INFO - Started process 53 to run task
[2025-06-29T01:07:03.497+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2025-06-28T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp51x74c76']
[2025-06-29T01:07:03.500+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask s3_upload
[2025-06-29T01:07:03.552+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2025-06-28T00:00:00+00:00 [running]> on host 40eb3c0b9201
[2025-06-29T01:07:03.633+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naspuka' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-28T00:00:00+00:00'
[2025-06-29T01:07:03.635+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-29T01:07:03.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-29T01:07:03.644+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 6, in upload_s3_pipeline
    file_path = ti.xcom.pull(task_ids='reddit_extraction', keys='return_value')
AttributeError: 'TaskInstance' object has no attribute 'xcom'
[2025-06-29T01:07:03.656+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=scheduled__2025-06-28T00:00:00+00:00, execution_date=20250628T000000, start_date=20250629T010703, end_date=20250629T010703
[2025-06-29T01:07:03.718+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task s3_upload ('TaskInstance' object has no attribute 'xcom'; 53)
[2025-06-29T01:07:03.891+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-29T01:07:03.951+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-29T01:07:03.953+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-29T09:54:22.318+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-29T09:54:22.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2025-06-28T00:00:00+00:00 [queued]>
[2025-06-29T09:54:22.339+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2025-06-28T00:00:00+00:00 [queued]>
[2025-06-29T09:54:22.340+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-29T09:54:22.346+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-06-28 00:00:00+00:00
[2025-06-29T09:54:22.358+0000] {standard_task_runner.py:63} INFO - Started process 53 to run task
[2025-06-29T09:54:22.363+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2025-06-28T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpitydot9d']
[2025-06-29T09:54:22.365+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask s3_upload
[2025-06-29T09:54:22.489+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2025-06-28T00:00:00+00:00 [running]> on host b1203407efc8
[2025-06-29T09:54:22.602+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naspuka' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-28T00:00:00+00:00'
[2025-06-29T09:54:22.604+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-29T09:54:22.617+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-29T09:54:22.617+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 6, in upload_s3_pipeline
    file_path = ti.xcom.pull(task_ids='reddit_extraction', keys='return_value')
AttributeError: 'TaskInstance' object has no attribute 'xcom'
[2025-06-29T09:54:22.626+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=scheduled__2025-06-28T00:00:00+00:00, execution_date=20250628T000000, start_date=20250629T095422, end_date=20250629T095422
[2025-06-29T09:54:22.686+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task s3_upload ('TaskInstance' object has no attribute 'xcom'; 53)
[2025-06-29T09:54:22.713+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-29T09:54:22.748+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-29T09:54:22.750+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
